// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wuqinqiang/helloword/dao/model"
)

func newPhrase(db *gorm.DB, opts ...gen.DOOption) phrase {
	_phrase := phrase{}

	_phrase.phraseDo.UseDB(db, opts...)
	_phrase.phraseDo.UseModel(&model.Phrase{})

	tableName := _phrase.phraseDo.TableName()
	_phrase.ALL = field.NewAsterisk(tableName)
	_phrase.PhraseID = field.NewString(tableName, "phrase_id")
	_phrase.Phrase = field.NewString(tableName, "phrase")
	_phrase.CreateTime = field.NewInt64(tableName, "create_time")
	_phrase.UpdateTime = field.NewInt64(tableName, "update_time")

	_phrase.fillFieldMap()

	return _phrase
}

type phrase struct {
	phraseDo phraseDo

	ALL        field.Asterisk
	PhraseID   field.String
	Phrase     field.String
	CreateTime field.Int64
	UpdateTime field.Int64

	fieldMap map[string]field.Expr
}

func (p phrase) Table(newTableName string) *phrase {
	p.phraseDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p phrase) As(alias string) *phrase {
	p.phraseDo.DO = *(p.phraseDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *phrase) updateTableName(table string) *phrase {
	p.ALL = field.NewAsterisk(table)
	p.PhraseID = field.NewString(table, "phrase_id")
	p.Phrase = field.NewString(table, "phrase")
	p.CreateTime = field.NewInt64(table, "create_time")
	p.UpdateTime = field.NewInt64(table, "update_time")

	p.fillFieldMap()

	return p
}

func (p *phrase) WithContext(ctx context.Context) *phraseDo { return p.phraseDo.WithContext(ctx) }

func (p phrase) TableName() string { return p.phraseDo.TableName() }

func (p phrase) Alias() string { return p.phraseDo.Alias() }

func (p *phrase) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *phrase) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["phrase_id"] = p.PhraseID
	p.fieldMap["phrase"] = p.Phrase
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
}

func (p phrase) clone(db *gorm.DB) phrase {
	p.phraseDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p phrase) replaceDB(db *gorm.DB) phrase {
	p.phraseDo.ReplaceDB(db)
	return p
}

type phraseDo struct{ gen.DO }

func (p phraseDo) Debug() *phraseDo {
	return p.withDO(p.DO.Debug())
}

func (p phraseDo) WithContext(ctx context.Context) *phraseDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p phraseDo) ReadDB() *phraseDo {
	return p.Clauses(dbresolver.Read)
}

func (p phraseDo) WriteDB() *phraseDo {
	return p.Clauses(dbresolver.Write)
}

func (p phraseDo) Session(config *gorm.Session) *phraseDo {
	return p.withDO(p.DO.Session(config))
}

func (p phraseDo) Clauses(conds ...clause.Expression) *phraseDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p phraseDo) Returning(value interface{}, columns ...string) *phraseDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p phraseDo) Not(conds ...gen.Condition) *phraseDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p phraseDo) Or(conds ...gen.Condition) *phraseDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p phraseDo) Select(conds ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p phraseDo) Where(conds ...gen.Condition) *phraseDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p phraseDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *phraseDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p phraseDo) Order(conds ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p phraseDo) Distinct(cols ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p phraseDo) Omit(cols ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p phraseDo) Join(table schema.Tabler, on ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p phraseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *phraseDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p phraseDo) RightJoin(table schema.Tabler, on ...field.Expr) *phraseDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p phraseDo) Group(cols ...field.Expr) *phraseDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p phraseDo) Having(conds ...gen.Condition) *phraseDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p phraseDo) Limit(limit int) *phraseDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p phraseDo) Offset(offset int) *phraseDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p phraseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *phraseDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p phraseDo) Unscoped() *phraseDo {
	return p.withDO(p.DO.Unscoped())
}

func (p phraseDo) Create(values ...*model.Phrase) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p phraseDo) CreateInBatches(values []*model.Phrase, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p phraseDo) Save(values ...*model.Phrase) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p phraseDo) First() (*model.Phrase, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Phrase), nil
	}
}

func (p phraseDo) Take() (*model.Phrase, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Phrase), nil
	}
}

func (p phraseDo) Last() (*model.Phrase, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Phrase), nil
	}
}

func (p phraseDo) Find() ([]*model.Phrase, error) {
	result, err := p.DO.Find()
	return result.([]*model.Phrase), err
}

func (p phraseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Phrase, err error) {
	buf := make([]*model.Phrase, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p phraseDo) FindInBatches(result *[]*model.Phrase, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p phraseDo) Attrs(attrs ...field.AssignExpr) *phraseDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p phraseDo) Assign(attrs ...field.AssignExpr) *phraseDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p phraseDo) Joins(fields ...field.RelationField) *phraseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p phraseDo) Preload(fields ...field.RelationField) *phraseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p phraseDo) FirstOrInit() (*model.Phrase, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Phrase), nil
	}
}

func (p phraseDo) FirstOrCreate() (*model.Phrase, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Phrase), nil
	}
}

func (p phraseDo) FindByPage(offset int, limit int) (result []*model.Phrase, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p phraseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p phraseDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p phraseDo) Delete(models ...*model.Phrase) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *phraseDo) withDO(do gen.Dao) *phraseDo {
	p.DO = *do.(*gen.DO)
	return p
}
