// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wuqinqiang/helloword/dao/model"
)

func newWordPhraseUsage(db *gorm.DB, opts ...gen.DOOption) wordPhraseUsage {
	_wordPhraseUsage := wordPhraseUsage{}

	_wordPhraseUsage.wordPhraseUsageDo.UseDB(db, opts...)
	_wordPhraseUsage.wordPhraseUsageDo.UseModel(&model.WordPhraseUsage{})

	tableName := _wordPhraseUsage.wordPhraseUsageDo.TableName()
	_wordPhraseUsage.ALL = field.NewAsterisk(tableName)
	_wordPhraseUsage.WordID = field.NewString(tableName, "word_id")
	_wordPhraseUsage.Word = field.NewString(tableName, "word")
	_wordPhraseUsage.LastReview = field.NewInt64(tableName, "last_review")
	_wordPhraseUsage.NextReview = field.NewInt64(tableName, "next_review")
	_wordPhraseUsage.NumRepetitions = field.NewInt32(tableName, "num_repetitions")
	_wordPhraseUsage.Status = field.NewString(tableName, "status")
	_wordPhraseUsage.CreateTime = field.NewInt64(tableName, "create_time")
	_wordPhraseUsage.UpdateTime = field.NewInt64(tableName, "update_time")

	_wordPhraseUsage.fillFieldMap()

	return _wordPhraseUsage
}

type wordPhraseUsage struct {
	wordPhraseUsageDo wordPhraseUsageDo

	ALL            field.Asterisk
	WordID         field.String
	Word           field.String
	LastReview     field.Int64
	NextReview     field.Int64
	NumRepetitions field.Int32
	Status         field.String
	CreateTime     field.Int64
	UpdateTime     field.Int64

	fieldMap map[string]field.Expr
}

func (w wordPhraseUsage) Table(newTableName string) *wordPhraseUsage {
	w.wordPhraseUsageDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wordPhraseUsage) As(alias string) *wordPhraseUsage {
	w.wordPhraseUsageDo.DO = *(w.wordPhraseUsageDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wordPhraseUsage) updateTableName(table string) *wordPhraseUsage {
	w.ALL = field.NewAsterisk(table)
	w.WordID = field.NewString(table, "word_id")
	w.Word = field.NewString(table, "word")
	w.LastReview = field.NewInt64(table, "last_review")
	w.NextReview = field.NewInt64(table, "next_review")
	w.NumRepetitions = field.NewInt32(table, "num_repetitions")
	w.Status = field.NewString(table, "status")
	w.CreateTime = field.NewInt64(table, "create_time")
	w.UpdateTime = field.NewInt64(table, "update_time")

	w.fillFieldMap()

	return w
}

func (w *wordPhraseUsage) WithContext(ctx context.Context) *wordPhraseUsageDo {
	return w.wordPhraseUsageDo.WithContext(ctx)
}

func (w wordPhraseUsage) TableName() string { return w.wordPhraseUsageDo.TableName() }

func (w wordPhraseUsage) Alias() string { return w.wordPhraseUsageDo.Alias() }

func (w *wordPhraseUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wordPhraseUsage) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 8)
	w.fieldMap["word_id"] = w.WordID
	w.fieldMap["word"] = w.Word
	w.fieldMap["last_review"] = w.LastReview
	w.fieldMap["next_review"] = w.NextReview
	w.fieldMap["num_repetitions"] = w.NumRepetitions
	w.fieldMap["status"] = w.Status
	w.fieldMap["create_time"] = w.CreateTime
	w.fieldMap["update_time"] = w.UpdateTime
}

func (w wordPhraseUsage) clone(db *gorm.DB) wordPhraseUsage {
	w.wordPhraseUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wordPhraseUsage) replaceDB(db *gorm.DB) wordPhraseUsage {
	w.wordPhraseUsageDo.ReplaceDB(db)
	return w
}

type wordPhraseUsageDo struct{ gen.DO }

func (w wordPhraseUsageDo) Debug() *wordPhraseUsageDo {
	return w.withDO(w.DO.Debug())
}

func (w wordPhraseUsageDo) WithContext(ctx context.Context) *wordPhraseUsageDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wordPhraseUsageDo) ReadDB() *wordPhraseUsageDo {
	return w.Clauses(dbresolver.Read)
}

func (w wordPhraseUsageDo) WriteDB() *wordPhraseUsageDo {
	return w.Clauses(dbresolver.Write)
}

func (w wordPhraseUsageDo) Session(config *gorm.Session) *wordPhraseUsageDo {
	return w.withDO(w.DO.Session(config))
}

func (w wordPhraseUsageDo) Clauses(conds ...clause.Expression) *wordPhraseUsageDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wordPhraseUsageDo) Returning(value interface{}, columns ...string) *wordPhraseUsageDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wordPhraseUsageDo) Not(conds ...gen.Condition) *wordPhraseUsageDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wordPhraseUsageDo) Or(conds ...gen.Condition) *wordPhraseUsageDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wordPhraseUsageDo) Select(conds ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wordPhraseUsageDo) Where(conds ...gen.Condition) *wordPhraseUsageDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wordPhraseUsageDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *wordPhraseUsageDo {
	return w.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (w wordPhraseUsageDo) Order(conds ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wordPhraseUsageDo) Distinct(cols ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wordPhraseUsageDo) Omit(cols ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wordPhraseUsageDo) Join(table schema.Tabler, on ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wordPhraseUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wordPhraseUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wordPhraseUsageDo) Group(cols ...field.Expr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wordPhraseUsageDo) Having(conds ...gen.Condition) *wordPhraseUsageDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wordPhraseUsageDo) Limit(limit int) *wordPhraseUsageDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wordPhraseUsageDo) Offset(offset int) *wordPhraseUsageDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wordPhraseUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *wordPhraseUsageDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wordPhraseUsageDo) Unscoped() *wordPhraseUsageDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wordPhraseUsageDo) Create(values ...*model.WordPhraseUsage) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wordPhraseUsageDo) CreateInBatches(values []*model.WordPhraseUsage, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wordPhraseUsageDo) Save(values ...*model.WordPhraseUsage) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wordPhraseUsageDo) First() (*model.WordPhraseUsage, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WordPhraseUsage), nil
	}
}

func (w wordPhraseUsageDo) Take() (*model.WordPhraseUsage, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WordPhraseUsage), nil
	}
}

func (w wordPhraseUsageDo) Last() (*model.WordPhraseUsage, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WordPhraseUsage), nil
	}
}

func (w wordPhraseUsageDo) Find() ([]*model.WordPhraseUsage, error) {
	result, err := w.DO.Find()
	return result.([]*model.WordPhraseUsage), err
}

func (w wordPhraseUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WordPhraseUsage, err error) {
	buf := make([]*model.WordPhraseUsage, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wordPhraseUsageDo) FindInBatches(result *[]*model.WordPhraseUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wordPhraseUsageDo) Attrs(attrs ...field.AssignExpr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wordPhraseUsageDo) Assign(attrs ...field.AssignExpr) *wordPhraseUsageDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wordPhraseUsageDo) Joins(fields ...field.RelationField) *wordPhraseUsageDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wordPhraseUsageDo) Preload(fields ...field.RelationField) *wordPhraseUsageDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wordPhraseUsageDo) FirstOrInit() (*model.WordPhraseUsage, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WordPhraseUsage), nil
	}
}

func (w wordPhraseUsageDo) FirstOrCreate() (*model.WordPhraseUsage, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WordPhraseUsage), nil
	}
}

func (w wordPhraseUsageDo) FindByPage(offset int, limit int) (result []*model.WordPhraseUsage, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wordPhraseUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wordPhraseUsageDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wordPhraseUsageDo) Delete(models ...*model.WordPhraseUsage) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wordPhraseUsageDo) withDO(do gen.Dao) *wordPhraseUsageDo {
	w.DO = *do.(*gen.DO)
	return w
}
