// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wuqinqiang/helloword/dao/model"
)

func newWord(db *gorm.DB, opts ...gen.DOOption) word {
	_word := word{}

	_word.wordDo.UseDB(db, opts...)
	_word.wordDo.UseModel(&model.Word{})

	tableName := _word.wordDo.TableName()
	_word.ALL = field.NewAsterisk(tableName)
	_word.WordID = field.NewString(tableName, "word_id")
	_word.Word = field.NewString(tableName, "word")
	_word.Phonetic = field.NewString(tableName, "phonetic")
	_word.Definition = field.NewString(tableName, "definition")
	_word.Difficulty = field.NewString(tableName, "difficulty")
	_word.CreateTime = field.NewInt64(tableName, "create_time")
	_word.UpdateTime = field.NewInt64(tableName, "update_time")

	_word.fillFieldMap()

	return _word
}

type word struct {
	wordDo wordDo

	ALL        field.Asterisk
	WordID     field.String
	Word       field.String
	Phonetic   field.String
	Definition field.String
	Difficulty field.String
	CreateTime field.Int64
	UpdateTime field.Int64

	fieldMap map[string]field.Expr
}

func (w word) Table(newTableName string) *word {
	w.wordDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w word) As(alias string) *word {
	w.wordDo.DO = *(w.wordDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *word) updateTableName(table string) *word {
	w.ALL = field.NewAsterisk(table)
	w.WordID = field.NewString(table, "word_id")
	w.Word = field.NewString(table, "word")
	w.Phonetic = field.NewString(table, "phonetic")
	w.Definition = field.NewString(table, "definition")
	w.Difficulty = field.NewString(table, "difficulty")
	w.CreateTime = field.NewInt64(table, "create_time")
	w.UpdateTime = field.NewInt64(table, "update_time")

	w.fillFieldMap()

	return w
}

func (w *word) WithContext(ctx context.Context) *wordDo { return w.wordDo.WithContext(ctx) }

func (w word) TableName() string { return w.wordDo.TableName() }

func (w word) Alias() string { return w.wordDo.Alias() }

func (w *word) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *word) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["word_id"] = w.WordID
	w.fieldMap["word"] = w.Word
	w.fieldMap["phonetic"] = w.Phonetic
	w.fieldMap["definition"] = w.Definition
	w.fieldMap["difficulty"] = w.Difficulty
	w.fieldMap["create_time"] = w.CreateTime
	w.fieldMap["update_time"] = w.UpdateTime
}

func (w word) clone(db *gorm.DB) word {
	w.wordDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w word) replaceDB(db *gorm.DB) word {
	w.wordDo.ReplaceDB(db)
	return w
}

type wordDo struct{ gen.DO }

func (w wordDo) Debug() *wordDo {
	return w.withDO(w.DO.Debug())
}

func (w wordDo) WithContext(ctx context.Context) *wordDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wordDo) ReadDB() *wordDo {
	return w.Clauses(dbresolver.Read)
}

func (w wordDo) WriteDB() *wordDo {
	return w.Clauses(dbresolver.Write)
}

func (w wordDo) Session(config *gorm.Session) *wordDo {
	return w.withDO(w.DO.Session(config))
}

func (w wordDo) Clauses(conds ...clause.Expression) *wordDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wordDo) Returning(value interface{}, columns ...string) *wordDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wordDo) Not(conds ...gen.Condition) *wordDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wordDo) Or(conds ...gen.Condition) *wordDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wordDo) Select(conds ...field.Expr) *wordDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wordDo) Where(conds ...gen.Condition) *wordDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wordDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *wordDo {
	return w.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (w wordDo) Order(conds ...field.Expr) *wordDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wordDo) Distinct(cols ...field.Expr) *wordDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wordDo) Omit(cols ...field.Expr) *wordDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wordDo) Join(table schema.Tabler, on ...field.Expr) *wordDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *wordDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wordDo) RightJoin(table schema.Tabler, on ...field.Expr) *wordDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wordDo) Group(cols ...field.Expr) *wordDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wordDo) Having(conds ...gen.Condition) *wordDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wordDo) Limit(limit int) *wordDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wordDo) Offset(offset int) *wordDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *wordDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wordDo) Unscoped() *wordDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wordDo) Create(values ...*model.Word) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wordDo) CreateInBatches(values []*model.Word, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wordDo) Save(values ...*model.Word) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wordDo) First() (*model.Word, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Word), nil
	}
}

func (w wordDo) Take() (*model.Word, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Word), nil
	}
}

func (w wordDo) Last() (*model.Word, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Word), nil
	}
}

func (w wordDo) Find() ([]*model.Word, error) {
	result, err := w.DO.Find()
	return result.([]*model.Word), err
}

func (w wordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Word, err error) {
	buf := make([]*model.Word, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wordDo) FindInBatches(result *[]*model.Word, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wordDo) Attrs(attrs ...field.AssignExpr) *wordDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wordDo) Assign(attrs ...field.AssignExpr) *wordDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wordDo) Joins(fields ...field.RelationField) *wordDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wordDo) Preload(fields ...field.RelationField) *wordDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wordDo) FirstOrInit() (*model.Word, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Word), nil
	}
}

func (w wordDo) FirstOrCreate() (*model.Word, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Word), nil
	}
}

func (w wordDo) FindByPage(offset int, limit int) (result []*model.Word, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wordDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wordDo) Delete(models ...*model.Word) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wordDo) withDO(do gen.Dao) *wordDo {
	w.DO = *do.(*gen.DO)
	return w
}
