// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePhrase = "phrase"

// Phrase mapped from table <phrase>
type Phrase struct {
	PhraseID   string `gorm:"column:phrase_id;type:TEXT" json:"phrase_id"`
	Phrase     string `gorm:"column:phrase;type:TEXT" json:"phrase"`
	CreateTime int64  `gorm:"column:create_time;type:BIGINT" json:"create_time"`
	UpdateTime int64  `gorm:"column:update_time;type:BIGINT" json:"update_time"`
}

// TableName Phrase's table name
func (*Phrase) TableName() string {
	return TableNamePhrase
}
