// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWord = "word"

// Word mapped from table <word>
type Word struct {
	WordID     string `gorm:"column:word_id;primaryKey" json:"word_id"`
	Word       string `gorm:"column:word;not null" json:"word"`
	Phonetic   string `gorm:"column:phonetic;not null" json:"phonetic"`
	Definition string `gorm:"column:definition;not null" json:"definition"`
	Difficulty string `gorm:"column:difficulty;not null" json:"difficulty"`
	CreateTime int64  `gorm:"column:create_time;not null" json:"create_time"`
	UpdateTime int64  `gorm:"column:update_time;not null" json:"update_time"`
}

// TableName Word's table name
func (*Word) TableName() string {
	return TableNameWord
}
