// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWordPhraseUsage = "word_phrase_usage"

// WordPhraseUsage mapped from table <word_phrase_usage>
type WordPhraseUsage struct {
	WordID         string `gorm:"column:word_id;type:TEXT" json:"word_id"`
	LastReview     int64  `gorm:"column:last_review;type:BIGINT" json:"last_review"`
	NextReview     int64  `gorm:"column:next_review;type:BIGINT" json:"next_review"`
	NumRepetitions int32  `gorm:"column:num_repetitions;type:INT" json:"num_repetitions"`
	Status         string `gorm:"column:status;type:TEXT" json:"status"`
	CreateTime     int64  `gorm:"column:create_time;type:BIGINT" json:"create_time"`
	UpdateTime     int64  `gorm:"column:update_time;type:BIGINT" json:"update_time"`
}

// TableName WordPhraseUsage's table name
func (*WordPhraseUsage) TableName() string {
	return TableNameWordPhraseUsage
}
